// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7w9oz8M1OFMSTQ2cA6cglela-4Bj3kIk',
    appId: '1:109916875810:web:5a0d702d88de0045eaee7b',
    messagingSenderId: '109916875810',
    projectId: 'flutterexam-e6be6',
    authDomain: 'flutterexam-e6be6.firebaseapp.com',
    storageBucket: 'flutterexam-e6be6.appspot.com',
    measurementId: 'G-MRG4KT16EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPgECyh7eQHeGCKWM0Ugf1oESK_1oec24',
    appId: '1:109916875810:android:c5ca5dcde0b1e548eaee7b',
    messagingSenderId: '109916875810',
    projectId: 'flutterexam-e6be6',
    storageBucket: 'flutterexam-e6be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYqwtdufK9gqUNr0w1E-4FIK_DXOwYIg',
    appId: '1:109916875810:ios:5eca443446b9c95deaee7b',
    messagingSenderId: '109916875810',
    projectId: 'flutterexam-e6be6',
    storageBucket: 'flutterexam-e6be6.appspot.com',
    iosBundleId: 'com.example.flutterexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYqwtdufK9gqUNr0w1E-4FIK_DXOwYIg',
    appId: '1:109916875810:ios:5eca443446b9c95deaee7b',
    messagingSenderId: '109916875810',
    projectId: 'flutterexam-e6be6',
    storageBucket: 'flutterexam-e6be6.appspot.com',
    iosBundleId: 'com.example.flutterexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7w9oz8M1OFMSTQ2cA6cglela-4Bj3kIk',
    appId: '1:109916875810:web:a18d90d6f916d127eaee7b',
    messagingSenderId: '109916875810',
    projectId: 'flutterexam-e6be6',
    authDomain: 'flutterexam-e6be6.firebaseapp.com',
    storageBucket: 'flutterexam-e6be6.appspot.com',
    measurementId: 'G-0754FWL103',
  );
}
